[package]
name = "arduino-goxlr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial2 = "0.2.15"
tokio = { version = "1.35.1", features = ["full"] }